resource_group_name     = "prod-resource-group"
aks_cluster_name        = "prod-aks-cluster"
location               = "East US"
node_count             = 1
kubernetes_version     = "1.21.2"
dns_prefix             = "prod-aks"
vm_size                = "Standard_B2s"
prefix                 = "prod"
address_space          = ["10.1.0.0/16"]
subnet_address_prefixes = ["10.1.1.0/24"]