aks_cluster_name        = "staging-aks-cluster"
resource_group_name     = "staging-resource-group"
location               = "East US"
node_count             = 1
kubernetes_version     = "1.21.2"
dns_prefix             = "staging-aks"
vm_size                = "Standard_B2s"
prefix                 = "staging"
address_space          = ["10.2.0.0/16"]
subnet_address_prefixes = ["10.2.1.0/24"]