aks_cluster_name     = "dev-aks-cluster"
resource_group_name  = "dev-resource-group"
location            = "East US"
node_count          = 1
kubernetes_version  = "1.21.2"
dns_prefix          = "dev-aks"
vm_size             = "Standard_B2s"
prefix              = "dev"
address_space       = ["10.0.0.0/16"]
subnet_address_prefixes = ["10.0.1.0/24"]